### ISSUE TITLE
Any reason to not update pyneurovault?

### ISSUE THREAD

**Issue by vsoch** [NeuroVault/neurovault_collection_downloader#1]
It's basically another wrapper to the API to do the same thing, any reason to not update it?

**Comment by chrisgorgo** [comment]
An external group needed a simple CLI for downloading images from collections, so I put this together in an hour. It would've been better to build on pyneurovault, but unfortunately, I did not think about it.

**Comment by vsoch** [comment]
Ah, okay, well if you remember next time, I'd be happy to help with this sort of thing. Pyneurovault does have a download example: https://github.com/NeuroVault/pyneurovault/blob/master/examples/download_example.py

And looking at the code a few years later, yes it definitely could be cleaned up a bit! But this always happens when programming - everything I do at time N-1 looks like the ugliest chicken scratch at time N.
